name: 'Update formula'
on:
  schedule:
    - cron: 0 0 * * *

jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: update
        continue-on-error: true
        run: |
          version=`curl -s https://api.github.com/repos/vdaas/vald-client-clj/releases/latest | jq -r '.tag_name'`
          ./update.sh ${version}

          git add valdcli.rb
          git commit -m ":robot: Update valdcli ${version}"

          git remote set-url origin "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

          git push origin master
        env:
          GITHUB_USER: vdaas-ci
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
