name: 'Update formula'
on:
  schedule:
    - cron: 5 * * * *

jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
        with:
          fetch-depth: 3
      - name: update
        continue-on-error: true
        run: |
          git checkout master

          version=`curl -s https://api.github.com/repos/vdaas/vald-client-clj/releases/latest | jq -r '.tag_name'`
          ./update.sh ${version}

          git config --global user.name "VDaaS org"
          git config --global user.email "ci@vdaas.org"

          git add valdcli.rb
          git commit -m ":robot: Update valdcli ${version}"

          git remote set-url origin "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

          git push origin master
        env:
          GITHUB_USER: vdaas-ci
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
